<?php require_once __DIR__.'/hg_site.php'; $nap=hg_nap(); ?>
<main class="ec-contact">
<section class="ec-contact-intro">
<div><p class="kicker">POĎME SA POROZPRÁVAŤ</p><h1>Vaša prevádzka.<br>Náš spoločný ďalší krok.</h1><p class="ec-lead">Objavte, čo môže Ellipse zjednodušiť práve u vás. Ukážeme vám systém na procesoch vášho hotela, reštaurácie či wellness.</p><div class="ec-direct"><a href="mailto:<?php echo hg_esc($nap['email']); ?>"><?php echo hg_esc($nap['email']); ?></a><a href="tel:<?php echo hg_esc($nap['phone']); ?>"><?php echo hg_esc($nap['phone_display']); ?></a></div><p class="ec-note">Už používate Ellipse? Zavolajte nám alebo kontaktujte náš tím nižšie.</p></div>
<aside class="ec-next"><span class="kicker">OD PRVÉHO KONTAKTU K DEMU</span><h2>Najprv spoznáme vás.</h2><ol><li><b>Povedzte nám o prevádzke</b><span>Čo dnes riešite a čo chcete zlepšiť.</span></li><li><b>Prejdeme si vaše procesy</b><span>Spoločne vyberieme relevantné moduly.</span></li><li><b>Ukážeme Ellipse v praxi</b><span>Dohodneme si prezentáciu a ďalšie kroky.</span></li></ol><a href="#contact-form">Dohodnúť ukážku <span aria-hidden="true">→</span></a></aside>
</section>
<section class="ec-contact-body" id="contact-form"><div class="ec-form-copy"><p class="kicker">DEMO A CENOVÁ PONUKA</p><h2>Začnime tým,<br>čo potrebujete vy.</h2><p>Napíšte nám pár slov o svojej prevádzke. Ozveme sa vám a pripravíme prezentáciu podľa vašich potrieb.</p><p class="ec-note">Odpovieme spravidla do jedného pracovného dňa.</p><a href="https://docs.google.com/forms/d/e/1FAIpQLSc9PjBaaLNX4nmlO8paIgT4ZRHdd5BrNB7WAvxOndFp8LwTUw/viewform?vc=0&amp;c=0&amp;w=1&amp;flr=0&amp;usp=mail_form_link" target="_blank" rel="noopener">Chcem vyplniť podklady pre cenovú ponuku →</a></div><div class="ec-form-card"><h3>Predstavte nám svoju prevádzku</h3><?php $fields=array('name'=>'Meno','surname'=>'Priezvisko','company'=>'Názov prevádzky','numbers'=>'Počet jednotiek','email'=>'E-mail','tel'=>'Mobil','text'=>'Čo by ste chceli vo svojej prevádzke zlepšiť?','submit'=>'Odoslať'); contacForm($fields); ?></div></section>
<section class="ec-people" id="persons"><p class="kicker">ĽUDIA ZA ELLIPSE</p><h2>Sme tu pre vás.</h2><div class="ec-people-grid">
<?php foreach(array(array('Petra Štefany','Office manager and support','petra.stefany'),array('Lenka Bolcárová','Office manager and relations','lenka.bolcarova'),array('Patrícia Chovancová','Office manager and websites','patricia.chovancova')) as $person): ?><article><h3><?php echo hg_esc($person[0]); ?></h3><p><?php echo hg_esc($person[1]); ?></p><a href="mailto:<?php echo hg_esc($person[2]); ?>@horecagroup.sk"><?php echo hg_esc($person[2]); ?>@horecagroup.sk</a><a href="tel:+421527871911">+421 52 787 1911</a></article><?php endforeach; ?></div></section>
<section class="ec-address"><div><p class="kicker">NÁJDETE NÁS V POPRADE</p><h2>HORECA GROUP s.r.o.</h2><p>Francisciho 20/B<br>058 01 Poprad, Slovensko</p><a href="https://www.google.com/maps/dir/?api=1&amp;destination=Francisciho+20,+058+01+Poprad" target="_blank" rel="noopener">Naplánovať cestu →</a></div><dl><dt>IČO</dt><dd>47912618</dd><dt>DIČ</dt><dd>2024148357</dd><dt>IČ DPH</dt><dd>SK2024148357</dd><dt>IBAN</dt><dd>SK45 8330 0000 0025 0068 1593</dd></dl></section>
</main>
