<?php
// Fallback associations; RS ellipse_meta.related_modules takes precedence.
return array(
  'nocny-prichod-bez-recepcie' => array('pms', 'self', 'pay', 'team'),
  'hotel-s-aquaparkom-jeden-areal-jeden-cip' => array('aqua', 'pms', 'pos', 'pay', 'crm'),
  'bezkontaktna-platba-a-doklad-ktory-host-dostane' => array('pos', 'pay'),
  'firemny-host-a-efaktura' => array('pms', 'pos', 'pay'),
  'darcekovy-poukaz-ktory-sa-da-predat-uplatnit-aj-najst-riesenie' => array('vouchers', 'pos', 'pms', 'pay'),
  'koniec-roka-a-tisice-expirovanych-poukazov-riesenie' => array('vouchers', 'pms', 'pos'),
  'podujatie-so-stropom' => array('events', 'pay', 'pos'),
  'domova-kniha-bez-osobneho-stretnutia' => array('self', 'pms', 'team'),
  'jedna-izba-pat-portalov-ziadna-duplicita' => array('channel', 'pms', 'booking'),
  'priamy-predaj-ktory-nezaostava-za-portalom-riesenie' => array('booking', 'pms', 'pay', 'channel', 'self'),
  'revpro-tempo-predaja-a-dynamicke-ceny' => array('revenue', 'pms', 'channel', 'booking'),
  'kartu-chcete-pri-rezervacii-peniaze-az-ked-pride' => array('pay', 'booking', 'pms'),
  'virtualna-karta-z-portalu-bez-prepisovania' => array('pay', 'channel', 'pms'),
  'qr-na-stole-objednavka-ucet-doklad-tringelt' => array('pos', 'pay', 'team'),
  'vecera-na-izbovy-ucet-rano-jeden-odchod-riesenie' => array('pos', 'pms', 'pay'),
  'viete-predajnu-cenu-food-cost-az-po-mesiaci' => array('pos', 'stock', 'team'),
  'nove-jedlo-na-listok-s-ai-kalkulaciou' => array('pos', 'stock'),
  'sklad-ktory-sa-hybe-s-tym-co-ste-predali-riesenie' => array('stock', 'pos', 'team'),
  'wellness-ktore-nejde-rezervovat-cez-recepciu-riesenie' => array('booking', 'pms', 'pay', 'team'),
  'permanentka-ktora-sa-neda-pozicat-na-slovo-riesenie' => array('crm', 'aqua', 'pay'),
  'kredit-na-cipe-namiesto-hotovosti-v-areali-riesenie' => array('aqua', 'pos', 'pay', 'crm'),
  'kongres-ktory-obsadi-salu-aj-izby-naraz-riesenie' => array('events', 'pms', 'pos', 'team'),
  'dve-rezervacie-na-jednej-posteli-riesenie' => array('pms', 'channel', 'team'),
  'upratana-izba-o-ktorej-recepcia-naozaj-vie-riesenie' => array('team', 'pms'),
  'majitel-apartmanu-chce-vytazok-nie-pristup-do-plachty-riesenie' => array('owners', 'pms', 'team'),
  'host-pise-o-polnoci-recepcia-spi-ella-nie-riesenie' => array('ella', 'messages', 'team', 'booking'),
  'opytate-sa-vlastnych-cisel-cez-mcp' => array('mcp', 'pms', 'pos'),
  'platba-priide-na-ucet-rezervacia-o-tom-este-nevie' => array('pms', 'pay'),
  'domova-kniha-a-statistika-bez-nedelnhost-prepisovania' => array('pms', 'self', 'team'),
  'host-ostava-este-noc-recepcia-o-tom-vie-az-rano-riesenie' => array('self', 'pms', 'pay', 'team'),
  'zaloha-proforma-a-faktura-ktore-o-sebe-vedia-riesenie' => array('pms', 'pos', 'pay', 'team'),
  'zlava-ktora-nepretecie-na-portal-riesenie' => array('crm', 'booking', 'self', 'vouchers'),
  'skupina-obsadi-salu-kalendar-musi-povedat-nie-riesenie' => array('events', 'team', 'pms'),
  'zmena-ktora-nie-je-pri-pocitaci-riesenie' => array('team', 'pms'),
);
